module.exports = {
  apps: [
    {
      name: 'sarcasm-wiki-dev',
      script: 'npm',
      args: 'run dev',
      cwd: './',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 4000,
      kill_timeout: 5000,
      wait_ready: false,
      listen_timeout: 10000,
      env: {
        NODE_ENV: 'development',
      },
      error_file: './logs/pm2-error.log',
      out_file: './logs/pm2-out.log',
      log_file: './logs/pm2-combined.log',
      time: true,
    },
    {
      name: 'sarcasm-wiki-dev-cron',
      script: 'npm',
      args: 'run dev:cron',
      cwd: './',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 4000,
      kill_timeout: 5000,
      wait_ready: false,
      listen_timeout: 10000,
      env: {
        NODE_ENV: 'development',
        ENABLE_CRON: 'true',
      },
      error_file: './logs/pm2-cron-error.log',
      out_file: './logs/pm2-cron-out.log',
      log_file: './logs/pm2-cron-combined.log',
      time: true,
    },
    {
      name: 'health-check',
      script: 'health-check.js',
      cwd: './',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      env: {
        PING_URL: process.env.PING_URL || 'https://sarcasm.wiki/',
        PING_INTERVAL: process.env.PING_INTERVAL || '3600',
        PM2_APP_NAME: 'sarcasm-wiki-dev',
      },
      error_file: './logs/health-check-error.log',
      out_file: './logs/health-check-out.log',
      log_file: './logs/health-check-combined.log',
      time: true,
    },
  ],
};

