[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.156.0"
  HUGO_ENABLEGITINFO = "true"

[[context.production.processing.images]]
  compress = true

[context.production]
  environment = { HUGO_ENV = "production" }
