interface AIBadgeProps {
  aiProvider?: string
  aiModel?: string
  contentType?: 'rewritten' | 'created'
  isOriginalContent?: boolean
}

export default function AIBadge({ 
  aiProvider, 
  aiModel, 
  contentType, 
  isOriginalContent 
}: AIBadgeProps) {
  // Не показываем бейдж, если нет AI информации
  if (!aiProvider || !aiModel) {
    return null
  }

  // Определяем иконку провайдера
  const getProviderIcon = (provider: string) => {
    switch (provider) {
      case 'Gemini':
        return '🔷'
      case 'OpenAI':
        return '🟢'
      case 'OpenRouter':
        return '🔀'
      default:
        return '🤖'
    }
  }

  // Определяем цвет провайдера
  const getProviderColor = (provider: string) => {
    switch (provider) {
      case 'Gemini':
        return '#4285f4'
      case 'OpenAI':
        return '#10a37f'
      case 'OpenRouter':
        return '#8b5cf6'
      default:
        return '#6b7280'
    }
  }

  // Определяем тип контента
  const getContentTypeInfo = () => {
    if (isOriginalContent) {
      return {
        label: 'Original Content',
        icon: '✨',
        color: '#f59e0b'
      }
    } else {
      return {
        label: 'Enhanced from Wikipedia',
        icon: '📝',
        color: '#06b6d4'
      }
    }
  }

  const providerColor = getProviderColor(aiProvider)
  const contentTypeInfo = getContentTypeInfo()

  return (
    <div className="ai-badge">
      {/* AI Provider Badge */}
      <div 
        className="ai-badge-provider"
        style={{
          border: `1px solid ${providerColor}20`,
          color: providerColor
        }}
      >
        <span>{getProviderIcon(aiProvider)}</span>
        <span>{aiProvider}</span>
      </div>

      {/* Model Name */}
      <div className="ai-badge-model">
        {aiModel}
      </div>

      {/* Content Type */}
      <div 
        className="ai-badge-content-type"
        style={{
          border: `1px solid ${contentTypeInfo.color}20`,
          color: contentTypeInfo.color
        }}
      >
        <span>{contentTypeInfo.icon}</span>
        <span>{contentTypeInfo.label}</span>
      </div>

      {/* Info Icon with Tooltip */}
      <div style={{
        marginLeft: 'auto',
        opacity: 0.6,
        cursor: 'help'
      }} title={`Generated by ${aiProvider} using ${aiModel} model. ${contentTypeInfo.label}.`}>
        <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor">
          <path d="M11,9H13V7H11M12,20C7.59,20 4,16.41 4,12C4,7.59 7.59,4 12,4C16.41,4 20,7.59 20,12C20,16.41 16.41,20 12,20M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,2M11,17H13V11H11V17Z" />
        </svg>
      </div>
    </div>
  )
}
